(defvar emacs-config-path (expand-file-name "init.d" user-emacs-directory))
(add-to-list 'load-path emacs-config-path)
(require 'init-file)
(require 'init-packages)
(require 'init-UI)
(use-package init-edit :defer 1.0)
(use-package init-app :defer 1.5)
(use-package init-codes)
(use-package init-notes :defer 1.5)
(provide 'init)
