(defvar emacs-config-path (expand-file-name "init.d" user-emacs-directory))
(add-to-list 'load-path emacs-config-path)
(require 'init-packages)
(require 'init-UI)
(require 'init-file)
(require 'init-app)
(require 'init-edit)
(require 'init-notes)
(require 'init-codes)
(provide 'init)
