(add-to-list 'load-path (expand-file-name "files" user-emacs-directory))
(require 'package-lisp)
(require 'UI-lisp)
(require 'file-lisp)
(require 'reader-lisp)
(require 'edit-lisp)
(require 'org-lisp)
(require 'prog-lisp)
(provide 'init)
