(provide 'web-download-methods)
(defun auto-download-from-web (url file)
  (if (memq system-type '(windows-nt cygwin ms-dos))
      (shell-command (concat "powershell Invoke-WebRequest -Uri " url " -OutFile " file))
    (shell-command (concat "curl " url " -o " file))
      ))
