(defun convert-ris2bib (file)
  (interactive "f")
  (prog1 (cond ((string-match "\\.ris\\'" file)
	  (let ((name (file-name-sans-extension file)))
	    (progn (shell-command (format "ris2xml %s.ris | xml2bib > %s.bib" name name))
		   (format "%s.bib" name))))
	 ((string-match "\\.bib\\'" file) file)
	 (t (progn (shell-command (format "ris2xml %s | xml2bib > %s.bib" file file))
		   (format "%s.bib" file))))
    ))
(provide 'config-convertor)
