(require 'config-lang-hooks)
(require 'config-lang-modes)
(require 'config-treesit)
(require 'config-protocol)
(require 'config-projectile)
(require 'config-treemacs)
(use-package config-snippets :defer 1.0)
(provide 'init-codes)
