(add-to-list 'load-path (expand-file-name "files/org" user-emacs-directory))
(defconst note-directory (get-directory-auto-create "" (if (eq system-type 'gnu/linux) "~/Documents/emacs/" "D:/emacs/")) "The directory of my notes.")
(require 'ref-lisp)
(require 'roam-lisp)
(require 'org-export-lisp)
(if (eq system-type 'gnu/linux)
    (require 'interleave-linux))
(provide 'org-lisp)
