(add-to-list 'load-path (expand-file-name "UI" emacs-config-path))
(require 'config-theme)
(require 'config-fonts)
(require 'config-buffer)
(require 'config-dashboard)
(require 'config-frame)
(provide 'init-UI)
